---
- name: Restart Nimbus
  service: name=storm-nimbus state=restarted
  when: storm_nimbus_enabled

- name: Restart Supervisor
  service: name=storm-supervisor state=restarted
  when: storm_supervisor_enabled

- name: Restart Logviewer
  service: name=storm-logviewer state=restarted
  when: storm_supervisor_enabled

- name: Restart UI
  service: name=storm-ui state=restarted
  when: storm_nimbus_enabled
