- name: OpenStack Alarm definitions
  monasca_alarm_definition:
    name: "{{item.name}}"
    description: "{{item.description | default('') }}"
    expression: "{{item.expression}}"
    keystone_token: "{{default_notification.keystone_token}}"
    match_by: "{{item.match_by | default(['hostname']) }}"
    monasca_api_url: "{{default_notification.monasca_api_url}}"
    severity: "{{item.severity | default('LOW') }}"
    alarm_actions:
      - "{{default_notification.notification_method_id}}"
    ok_actions:
      - "{{default_notification.notification_method_id}}"
    undetermined_actions:
      - "{{default_notification.notification_method_id}}"
  with_items:
    - { name: "VM Cpu usage", description: "CPU usage of a libvirt vm", expression: "avg(cpu.utilization_perc) > 90 times 3", match_by: [resource_id] }
    - { name: "Swift Health", description: "Basic swift healthcheck.", expression: "swift.healthcheck > 0"}  # Numerous other swift health checks exist but no alarms are defined in the default set
