---
- name: Configure storm.yaml
  template: dest="{{storm_root_dir}}/apache-storm-{{storm_version}}/conf/storm.yaml" owner={{storm_user}} group={{storm_group}} mode=644 src=storm.yaml.j2
  notify:
    - Restart Supervisor

- name: Setup Storm supervisor upstart script
  copy: dest={{supervisor_upstart_conf}} owner=root group=root mode=644 src=storm-supervisor.conf
  notify:
    - Restart Supervisor
  when: not use_systemd

- name: Setup Storm supervisor systemd script
  copy: dest={{supervisor_systemd_service}} owner=root group=root mode=644 src=storm-supervisor.service
  notify:
    - Restart Supervisor
  when: use_systemd

- name: Setup Storm Logviewer upstart script
  copy: dest={{logviewer_upstart_conf}} owner=root group=root mode=644 src=storm-logviewer.conf
  notify:
    - Restart Supervisor
  when: not use_systemd

- name: Setup Storm Logviewer systemd script
  copy: dest={{logviewer_systemd_service}} owner=root group=root mode=644 src=storm-logviewer.service
  notify:
    - Restart Supervisor
  when: use_systemd

- command: systemctl daemon-reload
  when: use_systemd

- meta: flush_handlers

- name: Enable Storm Supervisor
  service: name=storm-supervisor state=started enabled=yes

- name: Enable Storm Logviewer
  service: name=storm-logviewer state=started enabled=yes
