---
kafka_event:
  consumer_topic: events
  group: thresh-event
  producer_topic: alarm-state-transitions
kafka_metric:
  topic: metrics
  group: thresh-metric
monasca_conf_dir: /etc/monasca
thresh_conf_file: "{{ monasca_conf_dir }}/thresh-config.yml"
monasca_jar_dir: /opt/monasca
monasca_group: monasca
thresh_group: thresh
mysql_db: mon
thresh_tarball_base_url: http://tarballs.openstack.org/ci/monasca-thresh
thresh_version: 1.1.0-SNAPSHOT
thresh_statsd_host: localhost

skip_install: False
