---
influxdb_db: mon
monasca_conf_dir: /etc/monasca
monasca_log_dir: /var/log/monasca
monasca_jar_dir: /opt/monasca
monasca_persister_java: True
monasca_persister_java_opts: -Xmx1g
persister_version: 1.1.0-SNAPSHOT
persister_tarball_base_url: http://tarballs.openstack.org/ci/monasca-persister
persister_admin_connector_port: 8091
persister_app_connector_port: 8090

skip_install: False
