---
influxdb_schema_enabled: true
kafka_topics_enabled: true
mysql_schema_enabled: true
winchester_schema_enabled: true
influxdb_admin: root
influxdb_admin_password: root
influxdb_dbname: mon
influxdb_replication_factor: 1
influxdb_retention_policy: "90d"
influxdb_shard_duration: "7d"
mysql_admin: root
zookeeper_hosts: "localhost:2181"

mysql_root_dir: /var/lib/mysql
monasca_schema_file: "{{mysql_root_dir}}/mon.sql"
winchester_schema_file: "{{mysql_root_dir}}/winchester.sql"

kafka_events_partitions: 12
kafka_metrics_partitions: 64
# This should be the number of systems running the Notification Engine
kafka_retry_notifications_partitions: 3
kafka_replicas: 3

kafka_topics:
  metrics: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_metrics_partitions }}" }
  events: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  raw-events: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  transformed-events: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  stream-definitions: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  transform-definitions: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  alarm-state-transitions: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  alarm-notifications: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_events_partitions }}" }
  retry-notifications: { replicas: "{{ kafka_replicas }}", partitions: "{{ kafka_retry_notifications_partitions }}" }
